/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/Aside/index.vue')['default']
    GoodsItem: typeof import('./src/components/GoodsItem/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    PayDialog: typeof import('./src/components/PayDialog/index.vue')['default']
    Payment: typeof import('./src/components/Payment/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('./src/components/Toast/index.vue')['default']
  }
}
